import type { NextPage } from "next";
import Head from "next/head";
import SideBar from "../components/SideBar";
import { FiSearch } from "react-icons/fi";
import "../features/musicSlice";
import Styles from "../styles/page/index.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { getData } from "../features/musicSlice";

import Card from "../components/Card";
import { IReduxData } from "../components/types";
const Home: NextPage = () => {
  const { data, isLoading } = useSelector(
    (state: { musicData: { data: []; isLoading: boolean } }) => state.musicData
  );
  console.log(10);

  const dispatch = useDispatch();
  useEffect(() => {
    dispatch<any>(getData());
  }, []);
  return (
    <div className="">
      <Head>
        <title>Do-tify -music App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={Styles.home}>
        <div className={Styles.row}>
          {isLoading
            ? "Loading"
            : data.map((item: IReduxData) => {
                console.log(item?.key);

                return (
                  <Card
                    img={item?.images?.coverart}
                    desc={item.share.subject}
                    title={item?.title}
                    key={item?.key}
                  />
                );
              })}
        </div>
      </section>
    </div>
  );
};

export default Home;
