import type { NextPage } from "next";
import Head from "next/head";
import { FiSearch } from "react-icons/fi";
import { BsFillPlayCircleFill } from "react-icons/bs";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Do-tify -music App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className=""></section>
    </div>
  );
};

export default Home;
