import type { NextPage } from "next";
import Head from "next/head";
import SideBar from "../components/SideBar";
import { FiSearch } from "react-icons/fi";
import { BsFillPlayCircleFill } from "react-icons/bs";
import "../features/musicSlice";
import Styles from "../styles/page/index.module.css";
import { useDispatch, useSelector } from "react-redux";
import { useEffect } from "react";
import { getData } from "../features/musicSlice";
import Link from "next/link";
// import Card from "../components/Card";
// import { IReduxData } from "../components/types";
const Home: NextPage = () => {
  const { data, isLoading } = useSelector(
    (state: { musicData: { data: []; isLoading: boolean } }) => state.musicData
  );
  console.log(10);

  const dispatch = useDispatch();
  useEffect(() => {
    dispatch<any>(getData());
  }, []);
  return (
    <div className="">
      <Head>
        <title>Do-tify -music App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={Styles.home}>
        <div className={Styles.row}>
          {isLoading
            ? "Loading"
            : data.map((item: any) => {
                console.log(item?.key);

                return (
                  // <Card
                  //   img={item?.images?.coverart}
                  //   desc={item.share.subject}
                  //   title={item?.title}
                  //   key={item?.key}
                  // />
                  <Link href={"/song/" + item.key}>
                    <div className={Styles.card}>
                      <img
                        className={Styles.card_img}
                        src={item?.images?.coverart}
                        alt="image"
                      />
                      <p className={Styles.desc}>{item?.share?.subject}</p>
                      <div className={Styles.playOver}>
                        <p className={Styles.playIcon}>
                          <BsFillPlayCircleFill />
                        </p>
                      </div>
                    </div>
                  </Link>
                );
              })}
        </div>
      </section>
    </div>
  );
};

export default Home;
